### ISSUE TITLE
Classe não encontrada e problemas em alguns métodos

### ISSUE THREAD

**Issue by lessandronp** [arthurgregorio/library#10]
Oi Arthur, estive baixando seu código, porém tem alguns referências não encontradas:

import br.eti.arthurgregorio.library.domain.model.entities.security.User_;
na interface UserRepository
import br.eti.arthurgregorio.library.domain.model.entities.security.Group_;
na interface GroupRepository
Na classe Group, está exibindo o seguinte erro: The Java field for attribute "grants" is final no
atributo:     
@OneToMany(mappedBy = "group", fetch = EAGER, cascade = {REMOVE})
private final List<Grant> grants;

A princípio seria isso, estou usando JDK 8 e Wildfly 10.1.
Abs,
Att,
Lessandro

**Comment by arthurgregorio** [comment]
Olá, as entidades que tem underscore no final (User_ ou Grou_) são entidades geradas pelo JPA Model Gen. Basta realizar um clean install com o maven que as classes são geradas.

Sobre o erro reportado na classe de grupos com os grants, não consegui reproduzir, aqui esta normal.
